### ISSUE TITLE
Update Build Image size

### ISSUE THREAD

**Issue by gil0109** [BCDevExchange/simple-shiny-test#15]
Update JSON to increase Memory for Build otherwise build fails...

 			"runPolicy": "Serial",
 -			"resources": {},
 +			"resources": {
 +                            "limits": {
 +                                "memory": "2Gi"
 +                            },
 +                            "requests": {
 +                                "memory": "2Gi"
 +                            }
 +			},

**Comment by ateucher** [comment]
Thanks @gil0109 - I've just updated `openshift-template.json` as you suggested, but made it configurable via the `BUILD_MEMORY` parameter with a default of "2Gi".
