### ISSUE TITLE
Using ui.R + server.R instead of app.R

### ISSUE THREAD

**Issue by daattali** [BCDevExchange/simple-shiny-test#3]
In a real shiny app it's better to separate your app code into two separate files (ui+server), to separate view from logic. Right now the deployment assumes an app.R file is used

**Comment by ateucher** [comment]
Agreed. I'll add some instructions around this. Thanks

**Comment by ateucher** [comment]
It works with ui.R + server.R as is. I'll update the README

**Comment by daattali** [comment]
Awesome, thanks Andy
