### ISSUE TITLE
Support installing packages from GitHub

### ISSUE THREAD

**Issue by daattali** [BCDevExchange/simple-shiny-test#5]
Currently this deployment infrastructure supports a `packages.txt` file which lets you list the R packages you need to be installed. These R packages will be installed from the official R package repository (CRAN) using the `install.packages('<packagename>')` command.

However, in the R ecosystem, it is common to host a package on GitHub and to install it from GitHub.  Many shiny apps need to use packages that are available on GitHub but not on CRAN. These packages are installed using `devtools::install_github('<github_user>/<github_repo>')`. It would be useful to allow us to list GitHub packages as well as CRAN packages in the config file.

**Comment by ateucher** [comment]
Thanks @daattali - serendipitously, I was just working on this today. I should have a method ready to go tomorrow or the next day.

**Comment by ateucher** [comment]
@daattali I've implemented this in #6. Can you take a look and see if it makes sense to you before I merge?
