### ISSUE TITLE
Dockerfile silently continues when an R package fails to install

### ISSUE THREAD

**Issue by daattali** [BCDevExchange/simple-shiny-test#7]
I suspect this is what happens before I had 'tidyverse' in my `packages.txt` file, but the package was not available on the image. The only way I can see that happening is if it tried to install the package, ran into an error, and simply continued with setting up the rest of the image.

An easy way to check this would be to add a random string into packages.txt as a package that should definitely fail, and see if docker complains and stops or if it lets you think everything was ok.

**Comment by ateucher** [comment]
I've discovered something a bit crazy - when a package isn't available, the 'warning' that `install.packages` throws is actually just a message, so can't elevate to an error with `options(warn = 2)` or use `tryCatch` on it.

**Comment by ateucher** [comment]
If you can think of anything more elegant than this, I'd love to hear it:

```r
if (grepl('is not available', paste(capture.output(install.packages(c($R_LIBS))), collapse = ''))) stop('Package not available', call. = FALSE)
```

**Comment by daattali** [comment]
That's fine for now, unless you wanted to ask the person who was in charge
of Rtravis (I think it may have been craig citro?) about how travis handles
it. But anything that'll stop the process when a package fails is good

**Comment by ateucher** [comment]
Ah, that's a good idea. I'll investigate there. Even that doesn't cause Docker to stop the build though, so I need to do more digging

**Comment by ateucher** [comment]
Ok I think this is fixed. One thing has changed however: You will need to list your packages in `packages.txt` as `ggplot2 dplyr plotly` (i.e., no quotes, separated by spaces). Same goes for `gh-packages.txt`. I've also updated the README to reflect this

**Comment by daattali** [comment]
Awesome! The side effect is better I think,  it's easier to type and also
now it's consistent across all the package config files

**Comment by ateucher** [comment]
Agreed!
