### ISSUE TITLE
Consider copying over ALL files under app/ folder instead of only .R files

### ISSUE THREAD

**Issue by daattali** [BCDevExchange/simple-shiny-test#8]
It makes it a bit awkward to be forced to put everything inside the data or www folders because some things don't belong there.  If it's very important to not allow arbitrary files under `app/`, then it needs to be clearly documented that only .R files get copied over.

**Comment by ateucher** [comment]
I don't think there's any harm in this. I'll implement copying over the entire `app` directory and put a line in the README advising to keep unnecessary stuff out of there.

**Comment by ateucher** [comment]
Closed in 9c3ef406b8dd632e4bfc59b9ad1ab73e59bbb48e
