### ISSUE TITLE
Should packages.txt etc be one package per line rather than separated by spaces?

### ISSUE THREAD

**Issue by ateucher** [BCDevExchange/simple-shiny-test#9]
Instead of
```
ggplot2 dplyr
```

Would this be less error-prone?
```
ggplot2
dplyr
```

Could then `paste` into a sinlge line env var with:
```
cat packages.txt | paste -s -d ' ' -
```

On Windows would need to be:
```
cat packages.txt | dos2unix | paste -s -d ' ' -
```

@daattali any opinions?

**Comment by daattali** [comment]
Perhaps a bit less error prone, but I think separated by spaces is fine.
Previously, comma separated plus quotes, was a bit too much. But spaces or
new line, no big opinion from me

---
R-Shiny Consultant
http://deanattali.com/shiny

**Comment by ateucher** [comment]
Ok I'll leave it as is
